import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

// Initialize jsPDF with autotable
// const doc = new jsPDF();
// const { jsPDF } = doc.constructor;

export const generateTimetablePdf = (timetable, slots = []) => {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text('Class Timetable', 14, 22);
  
  // Department and Section
  doc.setFontSize(12);
  doc.text(`${timetable.department_name || 'Department'} - Section ${timetable.section || 'A'}`, 14, 32);
  
  // Semester and Date
  doc.setFontSize(10);
  doc.text(`Semester: ${timetable.semester || '1'}`, 14, 42);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 160, 42);
  
  // Prepare table data
  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
  const timeSlots = Array.from({ length: 8 }, (_, i) => `${i + 9}:00 - ${i + 10}:00`);
  
  // Create table headers
  const headers = ['Time', ...days];
  
  // Create table body
  const body = timeSlots.map((time, timeIndex) => {
    const row = [time];
    days.forEach((_, dayIndex) => {
      const slot = slots.find(s => 
        s.day_of_week === dayIndex && s.time_slot === timeIndex
      );
      row.push(slot ? 
        `${slot.subject_name || 'Subject'}\nRoom: ${slot.room_name || 'N/A'}\n${slot.teacher_name || 'Teacher: N/A'}` : 
        ''
      );
    });
    return row;
  });

  // Generate table
  doc.autoTable({
    head: [headers],
    body: body,
    startY: 50,
    styles: {
      fontSize: 8,
      cellPadding: 3,
      valign: 'middle',
      lineColor: [0, 0, 0],
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: 255,
      fontStyle: 'bold',
    },
    columnStyles: {
      0: { cellWidth: 25, fontStyle: 'bold' },
      ...Object.fromEntries(Array(days.length).fill(0).map((_, i) => [i + 1, { cellWidth: 33 }])),
    },
    didDrawPage: function (data) {
      // Footer
      const pageSize = doc.internal.pageSize;
      const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
      doc.setFontSize(8);
      doc.text(
        `Generated by ${timetable.generated_by_name || 'System'}`,
        data.settings.margin.left,
        pageHeight - 10
      );
    }
  });

  // Save the PDF
  doc.save(`timetable_${timetable.department_code || 'DEPT'}_${timetable.section || 'A'}.pdf`);
};